// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: itoa-mgmt/itoa-mgmt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pdf   string `protobuf:"bytes,1,opt,name=pdf,proto3" json:"pdf,omitempty"`
	Scale string `protobuf:"bytes,2,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *AnalyticsInput) Reset() {
	*x = AnalyticsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itoa_mgmt_itoa_mgmt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyticsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsInput) ProtoMessage() {}

func (x *AnalyticsInput) ProtoReflect() protoreflect.Message {
	mi := &file_itoa_mgmt_itoa_mgmt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsInput.ProtoReflect.Descriptor instead.
func (*AnalyticsInput) Descriptor() ([]byte, []int) {
	return file_itoa_mgmt_itoa_mgmt_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsInput) GetPdf() string {
	if x != nil {
		return x.Pdf
	}
	return ""
}

func (x *AnalyticsInput) GetScale() string {
	if x != nil {
		return x.Scale
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cdf string `protobuf:"bytes,1,opt,name=cdf,proto3" json:"cdf,omitempty"`
	Id  int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itoa_mgmt_itoa_mgmt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_itoa_mgmt_itoa_mgmt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_itoa_mgmt_itoa_mgmt_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetCdf() string {
	if x != nil {
		return x.Cdf
	}
	return ""
}

func (x *Result) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_itoa_mgmt_itoa_mgmt_proto protoreflect.FileDescriptor

var file_itoa_mgmt_itoa_mgmt_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x74, 0x6f, 0x61, 0x2d, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x69, 0x74, 0x6f, 0x61,
	0x2d, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x66, 0x61, 0x69,
	0x72, 0x77, 0x69, 0x6e, 0x64, 0x73, 0x30, 0x30, 0x39, 0x39, 0x2e, 0x69, 0x74, 0x6f, 0x61, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x38, 0x0a, 0x0e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x64, 0x66, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x64, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x2a, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x64, 0x66, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x64, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0x6a, 0x0a, 0x08, 0x49, 0x74, 0x6f,
	0x61, 0x4d, 0x67, 0x6d, 0x74, 0x12, 0x5e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x12, 0x26, 0x2e, 0x66, 0x61,
	0x69, 0x72, 0x77, 0x69, 0x6e, 0x64, 0x73, 0x30, 0x30, 0x39, 0x39, 0x2e, 0x69, 0x74, 0x6f, 0x61,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x77, 0x69, 0x6e, 0x64, 0x73, 0x30,
	0x30, 0x39, 0x39, 0x2e, 0x69, 0x74, 0x6f, 0x61, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x2c, 0x0a, 0x24, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x66, 0x61, 0x69, 0x72, 0x77, 0x69, 0x6e, 0x64, 0x73, 0x30, 0x30, 0x39,
	0x39, 0x2e, 0x69, 0x74, 0x6f, 0x61, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x62, 0x5a, 0x04, 0x2e,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itoa_mgmt_itoa_mgmt_proto_rawDescOnce sync.Once
	file_itoa_mgmt_itoa_mgmt_proto_rawDescData = file_itoa_mgmt_itoa_mgmt_proto_rawDesc
)

func file_itoa_mgmt_itoa_mgmt_proto_rawDescGZIP() []byte {
	file_itoa_mgmt_itoa_mgmt_proto_rawDescOnce.Do(func() {
		file_itoa_mgmt_itoa_mgmt_proto_rawDescData = protoimpl.X.CompressGZIP(file_itoa_mgmt_itoa_mgmt_proto_rawDescData)
	})
	return file_itoa_mgmt_itoa_mgmt_proto_rawDescData
}

var file_itoa_mgmt_itoa_mgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_itoa_mgmt_itoa_mgmt_proto_goTypes = []interface{}{
	(*AnalyticsInput)(nil), // 0: fairwinds0099.itoagrpc.AnalyticsInput
	(*Result)(nil),         // 1: fairwinds0099.itoagrpc.Result
}
var file_itoa_mgmt_itoa_mgmt_proto_depIdxs = []int32{
	0, // 0: fairwinds0099.itoagrpc.ItoaMgmt.CreateNewAnalytics:input_type -> fairwinds0099.itoagrpc.AnalyticsInput
	1, // 1: fairwinds0099.itoagrpc.ItoaMgmt.CreateNewAnalytics:output_type -> fairwinds0099.itoagrpc.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_itoa_mgmt_itoa_mgmt_proto_init() }
func file_itoa_mgmt_itoa_mgmt_proto_init() {
	if File_itoa_mgmt_itoa_mgmt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_itoa_mgmt_itoa_mgmt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyticsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itoa_mgmt_itoa_mgmt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itoa_mgmt_itoa_mgmt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_itoa_mgmt_itoa_mgmt_proto_goTypes,
		DependencyIndexes: file_itoa_mgmt_itoa_mgmt_proto_depIdxs,
		MessageInfos:      file_itoa_mgmt_itoa_mgmt_proto_msgTypes,
	}.Build()
	File_itoa_mgmt_itoa_mgmt_proto = out.File
	file_itoa_mgmt_itoa_mgmt_proto_rawDesc = nil
	file_itoa_mgmt_itoa_mgmt_proto_goTypes = nil
	file_itoa_mgmt_itoa_mgmt_proto_depIdxs = nil
}
